name: Deploy Infrastructure

on:
  push:
    branches:
      - assignment10
    paths:
      - 'terraform/**' 

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.8.2' 

    - name: Check AWS Credentials
      run: | 
        if [ -z "${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}" ] || [ -z "${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}" ]; then
          echo "AWS credentials are not set"
          exit 1
        else
          echo "AWS credentials are set"
        fi

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.TERRAFORM_AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.TERRAFORM_AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2 

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate
      
    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      env:
        TF_LOG: DEBUG
      run: terraform apply -auto-approve
