name: Test

on:
  pull_request:
    branches:
      - map

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm test

    - name: Generate code coverage report
      run: npm run coverage
